### ISSUE TITLE
Bootloop just after phone encryption

### ISSUE THREAD

**Issue by HorlogeSkynet** [ResurrectionRemix/android_vendor_resurrection#45]
Hello there,

I was running a build of Resurrection Remix (version: v5.7.3-20160807) for the Samsung Galaxy S3 4g (i9305) and after having encrypted the phone yesterday, it couldn't boot anymore.
Once the pattern entered (in order to decrypt ?), the phone stops its boot process and the logo animation seems to be infinite...

Is there a known bug with encrypted partition during boot ?
Thx !

**Comment by Mikescops** [comment]
No fix yet ?

**Comment by HorlogeSkynet** [comment]
Could you at least tell us why you closed that without any explication ?

**Comment by varund7726** [comment]
https://plus.google.com/+varund7726/posts/Lxvet83V6Rj

**Comment by HorlogeSkynet** [comment]
I don't understand everything, you've just sent a link about Android Nougat builders.
But actually the reason of this issue (and the others you closed by the way) was to talk about something which looks like a bug on a Marshmallow build.

This is not spaming or whatever you think it could be, but just a thread in order to open a discussion if someone else got the same trouble. Isn't it the right place to do this ?

**Comment by varund7726** [comment]
Didn't you read the very first line? 
"Attention users/maintainers" 
Your an end User right?

Also notice this 

"If you have device specific issues , *dont post on github .its NOT RR related*""

And 

"Please do NOT spam on RR github commits. We have gone open source so that we stay clean and allow users to build and contribute"


And lastly 
"
If you encounter issues , please mention them here on g+ not on github with a *proper logcat*" 

So all your answers in one .yes this is spamming because I've mentioned hundreds of times don't push your issues on githib and your issue is device specific. , its in the cm device tree , nothing to do with RR at all .

**Comment by varund7726** [comment]
And please show me where I've addressed this only to "android nougat builders"

**Comment by HorlogeSkynet** [comment]
Nougat: https://puu.sh/sI8Bd/fe2ec41ea7.png

I don't think it's a device specific issue, but I thought specifying which hardware I used would be good.

I don't see your point. Don't we have the right to open a "case" on a project 'cause it's open-source ? You can disable the issues threads on yours repo' I you think that's irrelevant.

Okay for G+, but people who don't know that, will come on these pages first, as long as it is a GitHub relative content...

**Comment by varund7726** [comment]
Yes its device specific .its not hardware specific. Our devices  nexus 6p ,one plus one , nexus 5x , nexus 6 ,op2 etc encrypt successfully .whereas old devices like i9300,305 don't .we don't modify device trees much .we use cm based device trees . so if you have an issue related to your device its not related to RR because we don't modify device specific stuff .

And yes for those who post in github , for those who don't know I will just link my post . and as for your "rights" not here you don't , this is our project so we make the rules here so please just quit the arrogance just because you feel offended that I closed your issue

**Comment by varund7726** [comment]
Also even if you wanted to post your issues here since your talking about open source , please note , this is the wrong repository you should be reporting in .this has nothing to do with encryption

Your issues should be posted here https://github.com/p-an/i9305-cm13-device

**Comment by HorlogeSkynet** [comment]
Let's continue by mail, would you ? I'm writing you one at the moment

**Comment by westcripp** [comment]
@HorlogeSkynet  encryption works only for google brand phones like nexus 6 or nexus 6p 

**its impossible to make it work on samsung devices ATM**  
Read this thread link below . you will get detailed information about the issue
https://forum.cyanogenmod.org/topic/115593-encryption-causes-bootloop/

**Comment by Timmmmaaahh** [comment]
@HorlogeSkynet Please understand that a lot of people are counting on Varund's work, distracting him with unrelated issues doesn't help anyone. For support, please resort to the community here: http://forum.xda-developers.com/galaxy-s3/development-i9305/rom-resurrection-remix-4-4-2-kitkat-v5-t2704828 (maintained by rodman01).

**Comment by HorlogeSkynet** [comment]
@westcripp Thanks for the links ! That's interesting. I've thought having done enough searches on the subject, but with "resurrection remix" in key words, nothing appeared... I should have tried with "cm" instead.

@Timmmmaaahh, I understand this, and I'm sorry then. But how was I supposed to know I've been disturbing anyone by opening an issue somewhere... ?

I'm done here ! I'll let you work
++
